import { ApolloProvider } from '@autospace/network/src/config/apollo';
import '@autospace/ui/app/globals.css';
import {
  SessionProvider,
  ToastContainer,
} from '@autospace/ui/components/molecules';
import { Header } from '@autospace/ui/components/organisms';
import { MenuItem } from '@autospace/util/types';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Autospace | Manager',
  description: 'Generated by create next app',
};

const MENUITEMS: MenuItem[] = [
  { label: 'New Garage', href: '/new-garage' },
  { label: 'Valets', href: '/valets' },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProvider>
        <ApolloProvider>
          <body className={`${inter.className} bg-gray-25`}>
            <Header menuItems={MENUITEMS} />
            {children}
            <ToastContainer />
          </body>
        </ApolloProvider>
      </SessionProvider>
    </html>
  );
}
